ENVIRONMENT = [
 ['IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN', 'LF', 'LF', 'LF', 'LF', 'IN'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP', 'SW', '00', '00', 'SW', 'DW', 'SW', '00', '00', 'SW', 'UP'],
 ['DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP', 'SW', 'SW', 'SW', 'SW', 'DW', 'SW', 'SW', 'SW', 'SW', 'UP'],
 ['IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN', 'RH', 'RH', 'RH', 'RH', 'IN']
]
